<?php declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StoreInfoExtra\ViewModel\StoreInfoExtra;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */
/** @var StoreInfoExtra $storeInfoExtra */

$storeInfoExtra = $viewModels->require(StoreInfoExtra::class);
?>

<?php if ($message = $storeInfoExtra->getNotices()): ?>
    <section class="message global border-b-2 border-slate-800 bg-slate-800 text-slate-50 shadow-none m-0 px-0 rounded-none font-normal">
        <div class="container text-center">
            <p><?= $escaper->escapeHtml($message); ?></p>
        </div>
    </section>
<?php endif; ?>
