<?php declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StoreInfoExtra\ViewModel\StoreInfoExtra;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */
/** @var StoreInfoExtra $storeInfoExtra */

$storeInfoExtra = $viewModels->require(StoreInfoExtra::class);

$socials = [
    [
        'type' => 'facebook',
        'link' => $storeInfoExtra->getFacebook(),
        'title' => __('Go to our %1 page', 'Facebook')
    ],
    [
        'type' => 'twitter',
        'link' => $storeInfoExtra->getTwitter() ? 'https://twitter.com/' . $storeInfoExtra->getTwitter() : '',
        'title' => __('Visit %1 on Twitter for more', $storeInfoExtra->getTwitter())
    ],
    [
        'type' => 'linkedin',
        'link' => $storeInfoExtra->getLinkedIn(),
        'title' => __('Go to our %1 page', 'LinkedIn')
    ],
    [
        'type' => 'instagram',
        'link' => $storeInfoExtra->getInstagram(),
        'title' => __('Explore our %1 page', 'Instagram')
    ],
    [
        'type' => 'mastodon',
        'link' => $storeInfoExtra->getMastodon(),
        'title' => __('Explore our %1 page', 'Mastodon')
    ],
    [
        'type' => 'pinterest',
        'link' => $storeInfoExtra->getPinterest(),
        'title' => __('Explore our %1 page', 'Pinterest')
    ],
    [
        'type' => 'youtube',
        'link' => $storeInfoExtra->getYouTube(),
        'title' => __('Go to our %1 page', 'YouTube')
    ],
    [
        'type' => 'vimeo',
        'link' => $storeInfoExtra->getVimeo(),
        'title' => __('View more on our %1 page', 'Vimeo')
    ]
];
?>

<div class="socials flex flex-wrap">
    <?php foreach ($socials as $social): ?>
        <?php if ($social['link']): ?>
            <a
                class="action p-2 <?= $social['type']; ?>"
                href="<?= $escaper->escapeHtml($social['link']); ?>"
                target="_blank"
                rel="noopener noreferrer"
                title="<?= $escaper->escapeHtml($social['title']); ?>"
            >
                <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor">
                    <use href="<?= $block->getViewFileUrl('Siteation_StoreInfoExtra::images/socials.svg'); ?>#<?= $social['type']; ?>" />
                </svg>
            </a>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
